### ISSUE TITLE
Exception for 'real' UserAgent header 

### ISSUE THREAD

**Issue by soyl** [ua-parser/uap-core#127]
Hi,

we are seeing a lot of parse failures in our logs for header values coming from actual client requests, but have no clue what is wrong:

Example:

    Mozilla/5.0 (Linux; Android 5.0; SM-N9005 Build/LRX21V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36

Exception:

    j.l.NullPointerException: null
    at j.util.regex.Matcher.quoteReplacement(Matcher.java:655) ~[na:1.7.0_51]
    at u.p.Device$DevicePattern$$anonfun$process$1.apply(Device.scala:17) ~[uap-scala_2.11-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at u.p.Device$DevicePattern$$anonfun$process$1.apply(Device.scala:15)
    at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:0.13.6]
    at u.p.Device$DevicePattern.process(Device.scala:15) ~[uap-scala_2.11-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at u.p.Device$DeviceParser$$anonfun$parse$1.apply(Device.scala:31)
    at u.p.Device$DeviceParser$$anonfun$parse$1.apply(Device.scala:30)
    at s.c.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124) ~[scala-library-2.11.6.jar:0.13.6]
    at s.c.immutable.List.foldLeft(List.scala:84) [scala-library-2.11.6.jar:0.13.6]
    at u.p.Device$DeviceParser.parse(Device.scala:30) ~[uap-scala_2.11-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at ua.parser.Parser.parse(Parser.scala:15)
    at u.p.CachingParser$$anonfun$parse$1.apply(CachingParser.scala:10)
    at u.p.CachingParser$$anonfun$parse$1.apply(CachingParser.scala:9)
    at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.6.jar:0.13.6]
    at u.p.CachingParser.parse(CachingParser.scala:9) ~[uap-scala_2.11-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at d.g.b.i.u.UserAgentParser$$anonfun$receive$1$$anonfun$1.apply(UserAgentParser.scala:19)

**Comment by tobie** [comment]
Sounds like you may want to ask your question here: https://github.com/ua-parser/uap-scala

**Comment by soyl** [comment]
Had the impression this was a regex issue. Ok, will do.

**Comment by russellwhitaker** [comment]
Works in at least one other implementation with no problems.
