### ISSUE TITLE
Tests fail in uap-java

### ISSUE THREAD

**Issue by tyler-sommer** [ua-parser/uap-core#290]
Hi there, it looks like one of the recent commits regarding Windows ua parsing broke something about the uap-java integration.

The last working commit from uap-core is: d3784c9

If you use a later commit from `uap-core` when running uap-java (latest) tests, you see an error like:

```
testParseOS(ua_parser.ParserTest)  Time elapsed: 0.037 sec  <<< FAILURE!
java.lang.AssertionError: Mozilla/5.0 (Windows U; Win NT 5.0; en-US; rv:1.8.0.2) Gecko/20060308 Firefox/1.5.0.2
Expected: is <{"family": "Windows", "major": "NT", "minor": "", "patch": "", "patch_minor": ""}>
     got: <{"family": "Windows", "major": "$1", "minor": "", "patch": "", "patch_minor": ""}>

	at org.junit.Assert.assertThat(Assert.java:780)
	at ua_parser.ParserTest.testOSFromYaml(ParserTest.java:139)
	at ua_parser.ParserTest.testParseOS(ParserTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

```

You can see in the output that the UA being tested seems to be malformed (Fairly certain it should be `Windows; U;` instead of `Windows U;`-- but even changing this in the `test_os.yaml` file matches the literal `$1` (as seen in the exception message).

It's not clear to me whether this is a problem in uap-java or not, so please let me know if I should open an issue there.

Let me know if I can provide any additional information. And as always, thanks for putting in all this effort for these libraries-- they really are some of the most useful around.

**Comment by nikunjb** [comment]
Seconding this comment above. I just left a comment on the commit that caused the breakage also.

**Comment by NeilP-global** [comment]
Same for uap-csharp.

https://github.com/ua-parser/uap-csharp/issues/34

Can we revert this until the official parsers support the change? It's bad that this commit was allowed when it's broken at least 2 ua-parser repos

**Comment by nikunjb** [comment]
Please see the discussion here also. https://github.com/ua-parser/uap-core/commit/6318cae5c8d610bb7d7da72ff9f4ff8b7c9ea6fc#commitcomment-26672070

**Comment by merlin-zaraza** [comment]
Fixed uap-java in [pull request](https://github.com/ua-parser/uap-java/pull/25)
